version: '3'

services:
  vue-ui:
    user: root
    build:
      dockerfile: Dockerfile-dev
    ports:
      - "7080:8080"
    container_name: vue-ui
    volumes:
       - .:/app
       - /app/node_modules
