  
version: '3'
services:
  vue-ui:
    build:
      context: ./my-app
      dockerfile: Dockerfile-dev
    ports:
      - "7001:8080"
    container_name: vue-ui
    volumes:
       - ./my-app:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules